/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#444749",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#bfc6dd",
        "on-primary-container": "#dad7ff",
        "surface-container-low": "#eff4ff",
        "inverse-on-surface": "#eaf1ff",
        "inverse-surface": "#233144",
        "on-primary-fixed-variant": "#3323cc",
        "on-background": "#0d1c2e",
        "on-primary-fixed": "#0f0069",
        "on-secondary-fixed-variant": "#3f4759",
        "on-secondary": "#ffffff",
        surface: "#f8f9ff",
        "surface-container": "#e6eeff",
        "surface-variant": "#d5e3fc",
        secondary: "#575e72",
        "on-surface-variant": "#464555",
        "outline-variant": "#c7c4d8",
        primary: "#3525cd",
        "on-surface": "#0d1c2e",
        "secondary-fixed": "#dbe2fa",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-tint": "#4d44e3",
        "primary-container": "#4f46e5",
        "surface-dim": "#ccdbf3",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#141b2c",
        background: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#5d6478",
        "surface-container-highest": "#d5e3fc",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#dadcde",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        success: "#10b981",
        "success-strong": "#1b5e20",
        "success-soft": "#e8f5e9",
        danger: "#c62828",
        "danger-soft": "#ffebee",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xl: "40px",
        sm: "8px",
        base: "4px",
        "container-max": "1280px",
        xs: "4px",
        gutter: "24px",
        xxl: "64px",
        lg: "24px",
        md: "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
