import { useState } from "react";
import { request } from "../api/client";
import type { ExamJobStatus } from "../types";

interface Props {
  onStartExam: (examId: string) => void;
}

interface FeedItem {
  id: number;
  kind: "user" | "bot" | "exam" | "error";
  text?: string;
  job?: ExamJobStatus;
  examId?: string;
}

let nextId = 1;

export default function ExamBuilder({ onStartExam }: Props) {
  const [feed, setFeed] = useState<FeedItem[]>([]);
  const [prompt, setPrompt] = useState("");
  const [busy, setBusy] = useState(false);

  async function submit() {
    const text = prompt.trim();
    if (!text || busy) return;
    setPrompt("");
    setBusy(true);
    setFeed((f) => [
      ...f,
      { id: nextId++, kind: "user", text },
      { id: nextId++, kind: "bot", text: "Đã hiểu! Mình đang tạo bộ đề cho bạn…" },
    ]);

    try {
      const created = await request<{ jobId: string }>("/api/exam-jobs", {
        method: "POST",
        body: { prompt: text },
      });
      const job = await pollJob(created.jobId);
      if (job.status === "completed" && job.examId) {
        setFeed((f) => [...f, { id: nextId++, kind: "exam", job, examId: job.examId! }]);
      } else {
        setFeed((f) => [...f, { id: nextId++, kind: "error", text: job.error ?? "Generation failed." }]);
      }
    } catch (e) {
      setFeed((f) => [...f, { id: nextId++, kind: "error", text: e instanceof Error ? e.message : "Request failed." }]);
    } finally {
      setBusy(false);
    }
  }

  async function pollJob(jobId: string): Promise<ExamJobStatus> {
    for (let i = 0; i < 20; i++) {
      await new Promise((r) => setTimeout(r, 500));
      const job = await request<ExamJobStatus>(`/api/exam-jobs/${jobId}`);
      if (job.status === "completed" || job.status === "failed") return job;
    }
    return { jobId, status: "failed", examId: null, error: "Timed out", progress: null };
  }

  return (
    <div className="builder">
      <div className="builder__feed">
        {feed.length === 0 && <p className="builder__empty">Ask ExamGenius for a mock exam — e.g. "5 câu hỏi AZ-900 mức Trung bình".</p>}
        {feed.map((item) => (
          <div key={item.id}>
            {item.kind === "user" && <div className="bubble bubble--user">{item.text}</div>}
            {item.kind === "bot" && <div className="bubble bubble--bot">{item.text}</div>}
            {item.kind === "error" && <div className="bubble bubble--error">{item.text}</div>}
            {item.kind === "exam" && item.examId && (
              <div className="exam-card">
                <div className="exam-card__badge">Generated by ExamGenius</div>
                <h3 className="exam-card__title">AZ-900 Cloud Concepts Practice</h3>
                <div className="exam-card__meta">
                  <span>5 Questions</span>
                  <span>10 Minutes</span>
                  <span>Practice</span>
                </div>
                <div className="exam-card__expiry">Available for 3 days</div>
                <button className="btn btn--primary" onClick={() => onStartExam(item.examId!)}>
                  Start exam
                </button>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="composer">
        <input
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && submit()}
          placeholder="Type your exam request here…"
          disabled={busy}
        />
        <button className="btn btn--primary" onClick={submit} disabled={busy || !prompt.trim()}>
          Send
        </button>
      </div>
    </div>
  );
}
